(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}}),d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка');return d}
const names={page_view:'Просмотры страниц',skin_view:'Открытия скинов',market_outbound:'Переходы на маркеты',favorite_add:'Добавления в избранное',portfolio_add:'Добавления в портфель',price_alert_add:'Ценовые уведомления',profit_alert_add:'Умные уведомления',price_report_open:'Открытия формы цены',price_report_submit:'Отправленные ошибки цен',pro_interest:'Интерес к PRO'};
function setup(){
 const grid=document.querySelector('.admin-grid'),layout=document.querySelector('.admin-layout');if(!grid||!layout)return;
 grid.insertAdjacentHTML('beforeend','<div class="stat"><span class="muted">Посетители 7д</span><b id="sVisitors">—</b></div><div class="stat"><span class="muted">Действия 7д</span><b id="sEvents">—</b></div><div class="stat"><span class="muted">Переходы в маркеты</span><b id="sOutbound">—</b></div><div class="stat"><span class="muted">Заявки PRO</span><b id="sProLeads">—</b></div><div class="stat"><span class="muted">Ошибки цен</span><b id="sReports">—</b></div>');
 layout.insertAdjacentHTML('beforebegin','<section class="section"><div class="section-head"><h2>Как используют AEROX</h2></div><div id="analyticsPanel" class="admin-analytics"><div class="panel muted">Загрузка аналитики...</div></div></section><section class="section"><div class="section-head"><h2>Сообщения об ошибках цен</h2></div><div id="priceReports"><div class="muted">Загрузка...</div></div></section>');
 const style=document.createElement('style');style.textContent='.admin-analytics{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.metric-row{display:grid;grid-template-columns:1fr auto auto;gap:12px;padding:9px 0;border-bottom:1px solid #173044}.metric-row small{color:#7894a5}.analytics-stack{display:grid;gap:14px}.daily-bars{display:grid;grid-template-columns:repeat(14,minmax(12px,1fr));gap:7px;height:128px;align-items:end;padding-top:18px}.daily-bar{min-height:3px;border-radius:5px 5px 2px 2px;background:linear-gradient(180deg,#23d6ff,#1479ff);position:relative}.daily-bar:hover:after{content:attr(data-tip);position:absolute;bottom:calc(100% + 6px);left:50%;transform:translateX(-50%);white-space:nowrap;background:#06131f;border:1px solid #1c526d;border-radius:7px;padding:5px 7px;font-size:11px;z-index:2}.price-report-admin{border:1px solid #273149;border-radius:14px;padding:14px;background:#0d131d;margin-bottom:12px}.price-report-admin header{display:flex;justify-content:space-between;gap:10px}.report-meta,.report-prices,.report-actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:9px}.report-meta{color:#7894a5;font-size:12px}.report-note{padding:9px;background:#07131e;border-radius:9px;margin-top:9px}.report-actions select{max-width:190px}.conversion{font-size:12px;color:#7f9bb0;margin-top:12px}@media(max-width:900px){.admin-analytics{grid-template-columns:1fr}}';document.head.appendChild(style);
}
async function loadExtra(){
 const me=await request('/api/admin/me');if(!me.is_admin)return;
 const [stats,data,reports]=await Promise.all([request('/api/admin/stats'),request('/api/admin/analytics'),request('/api/admin/price-reports')]);
 const eventMap=Object.fromEntries(data.events.map(x=>[x.event_name,x])),outbound=eventMap.market_outbound||{count:0,visitors:0};
 document.getElementById('sVisitors').textContent=stats.visitors_7d;document.getElementById('sEvents').textContent=stats.events_7d;document.getElementById('sOutbound').textContent=outbound.count;document.getElementById('sProLeads').textContent=stats.pro_leads;document.getElementById('sReports').textContent=stats.open_price_reports;
 const views=Number(eventMap.page_view?.visitors||0),skins=Number(eventMap.skin_view?.visitors||0),clicks=Number(eventMap.market_outbound?.visitors||0),maxDaily=Math.max(1,...data.daily.map(x=>Number(x.visitors)||0));
 const rows=(list,label)=>list.map(x=>`<div class="metric-row"><strong>${esc(label(x))}</strong><small>${Number(x.visitors)||0} посет.</small><b>${x.count??x.outbound??0}</b></div>`).join('')||'<div class="muted">Пока пусто.</div>';
 const daily=data.daily.map(x=>`<div class="daily-bar" style="height:${Math.max(3,Math.round(Number(x.visitors||0)/maxDaily*100))}%" data-tip="${esc(x.day)} · ${Number(x.visitors)||0} посет."></div>`).join('');
 document.getElementById('analyticsPanel').innerHTML=`<div class="analytics-stack"><div class="panel"><h3>Воронка за 30 дней</h3>${data.events.map(x=>`<div class="metric-row"><strong>${esc(names[x.event_name]||x.event_name)}</strong><small>${x.visitors} посет.</small><b>${x.count}</b></div>`).join('')||'<div class="muted">Данные появятся после первых посещений.</div>'}<div class="conversion">Посетитель → просмотр скина: ${views?(skins/views*100).toFixed(1):'0'}% · Просмотр скина → маркет: ${skins?(clicks/skins*100).toFixed(1):'0'}%</div></div><div class="panel"><h3>Переходы по площадкам</h3>${rows(data.markets,x=>`${x.market} · ${x.action==='buy'?'купить':x.action==='sell'?'продать':'без типа'}`)}</div><div class="panel"><h3>Источники пользователей</h3>${rows(data.sources,x=>`${x.source}${x.campaign&&x.campaign!=='—'?' / '+x.campaign:''}`)}</div></div><div class="analytics-stack"><div class="panel"><h3>Посетители по дням</h3><div class="daily-bars">${daily||'<div class="muted">Пока пусто.</div>'}</div></div><div class="panel"><h3>Популярные страницы</h3>${rows(data.pages,x=>x.page)}</div><div class="panel"><h3>Популярные скины</h3>${rows(data.items,x=>x.item_name)}</div></div>`;
 const root=document.getElementById('priceReports');root.innerHTML=reports.reports.length?reports.reports.map(x=>`<article class="price-report-admin"><header><strong>#${x.id} · ${esc(x.item_name)}</strong><span class="muted">${new Date(x.created_at).toLocaleString('ru-RU')}</span></header><div class="report-meta"><span>${esc(x.market)}</span><span>${esc(x.reason)}</span><span>${x.steamid?'Steam '+esc(x.steamid):'без входа'}</span></div><div class="report-prices"><span>AEROX: <b>${x.site_price==null?'—':'$'+Number(x.site_price).toFixed(2)}</b></span><span>Площадка: <b>${x.observed_price==null?'не указана':'$'+Number(x.observed_price).toFixed(2)}</b></span></div>${x.note?`<div class="report-note">${esc(x.note)}</div>`:''}<div class="report-actions"><select data-report-status="${x.id}"><option value="open" ${x.status==='open'?'selected':''}>Открыто</option><option value="reviewed" ${x.status==='reviewed'?'selected':''}>Проверено</option><option value="fixed" ${x.status==='fixed'?'selected':''}>Исправлено</option><option value="dismissed" ${x.status==='dismissed'?'selected':''}>Отклонено</option></select><button class="primary report-save" data-id="${x.id}">Сохранить</button></div></article>`).join(''):'<div class="panel muted">Сообщений пока нет.</div>';
 root.querySelectorAll('.report-save').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await request('/api/admin/price-reports/'+button.dataset.id,{method:'PUT',body:JSON.stringify({status:root.querySelector(`[data-report-status="${button.dataset.id}"]`).value})});button.textContent='Готово';await loadExtra()}catch(e){button.textContent=e.message}finally{setTimeout(()=>{button.disabled=false;button.textContent='Сохранить'},1000)}});
}
document.addEventListener('DOMContentLoaded',()=>{setup();setTimeout(()=>loadExtra().catch(()=>{}),250)});
})();
