(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}}),d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка');return d}
const names={page_view:'Просмотры страниц',skin_view:'Открытия скинов',market_outbound:'Переходы на маркеты',favorite_add:'Добавления в избранное',portfolio_add:'Добавления в портфель',price_alert_add:'Ценовые уведомления',profit_alert_add:'Умные уведомления',price_report_open:'Открытия формы цены',price_report_submit:'Отправленные ошибки цен',pro_interest:'Интерес к PRO'};
function setup(){
 const grid=document.querySelector('.admin-grid'),layout=document.querySelector('.admin-layout');if(!grid||!layout)return;
 grid.insertAdjacentHTML('beforeend','<div class="stat"><span class="muted">Посетители 7д</span><b id="sVisitors">—</b></div><div class="stat"><span class="muted">Действия 7д</span><b id="sEvents">—</b></div><div class="stat"><span class="muted">Ошибки цен</span><b id="sReports">—</b></div>');
 layout.insertAdjacentHTML('beforebegin','<section class="section"><div class="section-head"><h2>Как используют AEROX</h2></div><div id="analyticsPanel" class="admin-analytics"><div class="panel muted">Загрузка аналитики...</div></div></section><section class="section"><div class="section-head"><h2>Сообщения об ошибках цен</h2></div><div id="priceReports"><div class="muted">Загрузка...</div></div></section>');
 const style=document.createElement('style');style.textContent='.admin-analytics{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.metric-row{display:grid;grid-template-columns:1fr auto auto;gap:12px;padding:9px 0;border-bottom:1px solid #173044}.metric-row small{color:#7894a5}.price-report-admin{border:1px solid #273149;border-radius:14px;padding:14px;background:#0d131d;margin-bottom:12px}.price-report-admin header{display:flex;justify-content:space-between;gap:10px}.report-meta,.report-prices,.report-actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:9px}.report-meta{color:#7894a5;font-size:12px}.report-note{padding:9px;background:#07131e;border-radius:9px;margin-top:9px}.report-actions select{max-width:190px}.conversion{font-size:12px;color:#7f9bb0;margin-top:12px}@media(max-width:900px){.admin-analytics{grid-template-columns:1fr}}';document.head.appendChild(style);
}
async function loadExtra(){
 const me=await request('/api/admin/me');if(!me.is_admin)return;
 const [stats,data,reports]=await Promise.all([request('/api/admin/stats'),request('/api/admin/analytics'),request('/api/admin/price-reports')]);
 document.getElementById('sVisitors').textContent=stats.visitors_7d;document.getElementById('sEvents').textContent=stats.events_7d;document.getElementById('sReports').textContent=stats.open_price_reports;
 const counts=Object.fromEntries(data.events.map(x=>[x.event_name,Number(x.count)])),views=counts.page_view||0,skins=counts.skin_view||0,clicks=counts.market_outbound||0;
 document.getElementById('analyticsPanel').innerHTML=`<div class="panel"><h3>Действия за 30 дней</h3>${data.events.map(x=>`<div class="metric-row"><strong>${esc(names[x.event_name]||x.event_name)}</strong><small>${x.visitors} посет.</small><b>${x.count}</b></div>`).join('')||'<div class="muted">Данные появятся после первых посещений.</div>'}<div class="conversion">Переход страница → скин: ${views?(skins/views*100).toFixed(1):'0'}% · Скин → маркет: ${skins?(clicks/skins*100).toFixed(1):'0'}%</div></div><div><div class="panel"><h3>Популярные страницы</h3>${data.pages.map(x=>`<div class="metric-row"><strong>${esc(x.page)}</strong><span></span><b>${x.count}</b></div>`).join('')||'<div class="muted">Пока пусто.</div>'}</div><div class="panel" style="margin-top:14px"><h3>Популярные скины</h3>${data.items.map(x=>`<div class="metric-row"><strong>${esc(x.item_name)}</strong><span></span><b>${x.count}</b></div>`).join('')||'<div class="muted">Пока пусто.</div>'}</div></div>`;
 const root=document.getElementById('priceReports');root.innerHTML=reports.reports.length?reports.reports.map(x=>`<article class="price-report-admin"><header><strong>#${x.id} · ${esc(x.item_name)}</strong><span class="muted">${new Date(x.created_at).toLocaleString('ru-RU')}</span></header><div class="report-meta"><span>${esc(x.market)}</span><span>${esc(x.reason)}</span><span>${x.steamid?'Steam '+esc(x.steamid):'без входа'}</span></div><div class="report-prices"><span>AEROX: <b>${x.site_price==null?'—':'$'+Number(x.site_price).toFixed(2)}</b></span><span>Площадка: <b>${x.observed_price==null?'не указана':'$'+Number(x.observed_price).toFixed(2)}</b></span></div>${x.note?`<div class="report-note">${esc(x.note)}</div>`:''}<div class="report-actions"><select data-report-status="${x.id}"><option value="open" ${x.status==='open'?'selected':''}>Открыто</option><option value="reviewed" ${x.status==='reviewed'?'selected':''}>Проверено</option><option value="fixed" ${x.status==='fixed'?'selected':''}>Исправлено</option><option value="dismissed" ${x.status==='dismissed'?'selected':''}>Отклонено</option></select><button class="primary report-save" data-id="${x.id}">Сохранить</button></div></article>`).join(''):'<div class="panel muted">Сообщений пока нет.</div>';
 root.querySelectorAll('.report-save').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await request('/api/admin/price-reports/'+button.dataset.id,{method:'PUT',body:JSON.stringify({status:root.querySelector(`[data-report-status="${button.dataset.id}"]`).value})});button.textContent='Готово';await loadExtra()}catch(e){button.textContent=e.message}finally{setTimeout(()=>{button.disabled=false;button.textContent='Сохранить'},1000)}});
}
document.addEventListener('DOMContentLoaded',()=>{setup();setTimeout(()=>loadExtra().catch(()=>{}),250)});
})();
