(()=>{
 document.documentElement.dataset.profitScanner='v209-filter';
 const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>Number.isFinite(Number(n))?'$'+Number(n).toFixed(2):'—';let rows=[],meta=null;
 function skinId(hash){return encodeURIComponent(hash).replace(/%/g,'').slice(0,120)}
 function lisSlug(hash){return String(hash).normalize('NFKD').replace(/™/g,'').replace(/[|()]/g,' ').toLowerCase().replace(/[^\p{L}\p{N}★]+/gu,'-').replace(/^-+|-+$/g,'')}
 function marketUrl(market,row){const hash=row.market_hash_name;if(market==='skinport')return row.item_page||`https://skinport.com/market?search=${encodeURIComponent(hash)}`;if(market==='csfloat')return`https://csfloat.com/search?market_hash_name=${encodeURIComponent(hash)}`;if(market==='lisskins')return`https://lis-skins.com/market/csgo/${encodeURIComponent(lisSlug(hash))}/`;return'#'}
 function imageUrl(row){if(row.image)return row.image;const base=row.name.replace(/^★\s*/,'').replace(/^StatTrak™\s*/,'').split('|').map(x=>x.trim());return base.length>1?`https://specs.gg/assets/img/cs2_skins/${encodeURIComponent(base[0])}/${encodeURIComponent(base.slice(1).join(' | '))}.png`:''}
 function filteredRows(){const q=$('#scannerSearch').value.trim().toLowerCase(),minProfit=Math.max(0,Number($('#minProfit').value)||0),minRoi=Math.max(0,Number($('#minRoi').value)||0),maxBuy=Math.max(0,Number($('#maxBuy').value)||0);return rows.filter(x=>(!q||x.market_hash_name.toLowerCase().includes(q))&&Number(x.profit)>=minProfit&&Number(x.roi)>=minRoi&&(!maxBuy||Number(x.buy_price)<=maxBuy))}
 function draw(){const sort=$('#scannerSort').value,list=filteredRows();list.sort(sort==='roi'?(a,b)=>b.roi-a.roi:sort==='price'?(a,b)=>a.buy_price-b.buy_price:(a,b)=>b.profit-a.profit);summary(list);const root=$('#scannerResults');if(!list.length){root.innerHTML='<div class="panel empty">По выбранным условиям подтверждённых связок не найдено. Уменьши минимальную прибыль/ROI или увеличь максимальную цену покупки.</div>';return}root.innerHTML=list.map((x,i)=>{const detail=`skin.html?id=${skinId(x.market_hash_name)}&hash=${encodeURIComponent(x.market_hash_name)}`,buy=marketUrl(x.buy_market,x),sell=marketUrl('csfloat',x);return`<article class="profit-row"><a class="profit-skin" href="${detail}"><img src="${esc(imageUrl(x))}" alt="" loading="lazy" onerror="this.style.opacity=.15"><div><span class="verified-pill">✓ CASH ORDER</span><strong>${esc(x.name)}</strong><small>${esc(x.condition||'—')} · ${x.quantity} лотов · #${i+1}</small></div></a><div class="profit-cell"><small>Купить: ${esc(x.buy_market_name)}</small><strong>${money(x.buy_price)}</strong></div><div class="profit-cell"><small>Продать: CSFloat</small><strong>${money(x.sell_order)}</strong></div><div class="profit-cell reserve-cell"><small>После комиссии / резерв</small><strong>${money(x.net_after_fee)} / −${money(x.reserve)}</strong></div><div class="profit-cell"><small>Расчётный плюс</small><strong class="profit-value">+${money(x.profit)}</strong><small>ROI ${Number(x.roi).toFixed(1)}%</small></div><div class="profit-actions"><a class="secondary outbound" data-market="${x.buy_market}" data-action="buy" data-item="${esc(x.name)}" href="${esc(buy)}" target="_blank" rel="noopener noreferrer">Купить</a><a class="primary outbound" data-market="csfloat" data-action="sell" data-item="${esc(x.name)}" href="${esc(sell)}" target="_blank" rel="noopener noreferrer">Продать</a><a class="ghost" href="${detail}">Проверить</a></div></article>`}).join('');root.querySelectorAll('.outbound').forEach(a=>a.addEventListener('click',()=>window.AeroxAnalytics?.track('market_outbound',{market:a.dataset.market,action:a.dataset.action,item_name:a.dataset.item})))}
 function summary(list=filteredRows()){const box=$('#scannerSummary');box.hidden=false;const bestProfit=list.slice().sort((a,b)=>b.profit-a.profit)[0],bestRoi=list.slice().sort((a,b)=>b.roi-a.roi)[0],time=meta?.updated_at?new Date(meta.updated_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):'—';box.innerHTML=`<div class="scanner-stat"><span>Найдено связок</span><strong>${list.length}</strong><small>соответствуют фильтрам</small></div><div class="scanner-stat"><span>Лучшая прибыль</span><strong class="up">${bestProfit?'+'+money(bestProfit.profit):'—'}</strong><small>${bestProfit?esc(bestProfit.name):'по текущим фильтрам'}</small></div><div class="scanner-stat"><span>Лучший ROI</span><strong class="up">${bestRoi?Number(bestRoi.roi).toFixed(1)+'%':'—'}</strong><small>${bestRoi?esc(bestRoi.name):'по текущим фильтрам'}</small></div><div class="scanner-stat"><span>Проверено</span><strong>${time}</strong><small>свежие cash-источники</small></div>`}
 async function scan(){const button=$('#scanButton'),status=$('#scannerStatus'),params=new URLSearchParams({min_profit:$('#minProfit').value,min_roi:$('#minRoi').value,max_buy:$('#maxBuy').value,sell_fee:$('#sellFee').value,reserve:$('#reserve').value,limit:'150'});button.disabled=true;button.textContent='Сканируем…';status.hidden=false;status.innerHTML='<strong>Проверяем рынок…</strong><span class="muted">Сопоставляем тысячи предметов. Обычно это занимает несколько секунд.</span>';$('#scannerResults').innerHTML='';try{const r=await fetch('/api/profit-scanner?'+params),d=await r.json();if(!r.ok)throw Error(d.error||'Сканер временно недоступен');rows=Array.isArray(d.rows)?d.rows:[];meta=d;draw();status.hidden=true;window.AeroxAnalytics?.track('profit_scanner_run')}catch(e){status.hidden=false;status.innerHTML=`<strong>Не удалось обновить сканер</strong><span class="muted">${esc(e.message)}. Попробуй ещё раз немного позже.</span>`}finally{button.disabled=false;button.textContent='Сканировать рынок'}}
 $('#scannerForm').addEventListener('submit',e=>{e.preventDefault();scan()});$('#scannerSearch').addEventListener('input',draw);$('#scannerSort').addEventListener('change',draw);['#minProfit','#minRoi','#maxBuy'].forEach(id=>$(id).addEventListener('input',draw));scan();
})();
