const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {URL}=require('url');
const {Pool}=require('pg');
const NODE_ENV=process.env.NODE_ENV||'development',HOST=process.env.HOST||'0.0.0.0',PORT=Number(process.env.PORT||3000),ALLOWED_ORIGIN=process.env.ALLOWED_ORIGIN||'*',LOG_LEVEL=process.env.LOG_LEVEL||'info';
const SESSION_SECRET=process.env.SESSION_SECRET||'skinforge-dev-change-me',STEAM_API_KEY=process.env.STEAM_API_KEY||'',STEAM_OPENID='https://steamcommunity.com/openid/login',DATABASE_URL=process.env.DATABASE_URL||'',ADMIN_SETUP_KEY=process.env.ADMIN_SETUP_KEY||'';
const ROOT=__dirname,CACHE_MS=5*60*1000,cache=new Map();let lastGoodItems=null,lastGoodItemsAt=null,db=null,dbReady=null;
const diag={started_at:new Date().toISOString(),skinport:{ok:null,last_success:null,last_error:null,item_count:0,raw_item_count:0},steam:{ok:null,last_success:null,last_error:null}};
function log(level,message,meta={}){const l={error:0,warn:1,info:2,debug:3};if((l[level]??2)>(l[LOG_LEVEL]??2))return;console.log(JSON.stringify({time:new Date().toISOString(),level,message,...meta}))}
function headers(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Access-Control-Allow-Origin',ALLOWED_ORIGIN);res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(NODE_ENV==='production')res.setHeader('Strict-Transport-Security','max-age=15552000; includeSubDomains')}
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}function json(res,s,d){send(res,s,JSON.stringify(d))}
function origin(req){return `${String(req.headers['x-forwarded-proto']||'http').split(',')[0].trim()}://${req.headers.host}`}
function hmac(v){return crypto.createHmac('sha256',SESSION_SECRET).update(String(v)).digest('hex')}function eq(a,b){const A=Buffer.from(String(a||'')),B=Buffer.from(String(b||''));return A.length===B.length&&crypto.timingSafeEqual(A,B)}
function state(){const t=Date.now().toString();return `${t}.${hmac('state:'+t)}`}function stateOK(v){const[t,s]=String(v||'').split('.'),age=Date.now()-Number(t);return !!t&&!!s&&eq(s,hmac('state:'+t))&&age>=0&&age<600000}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}))}
function steamId(req){const x=cookies(req).sf_session||'',i=x.lastIndexOf('.');if(i<1)return null;const id=x.slice(0,i),sig=x.slice(i+1);return /^\d{17}$/.test(id)&&eq(sig,hmac('session:'+id))?id:null}
function setSession(res,id){res.setHeader('Set-Cookie',`sf_session=${id}.${hmac('session:'+id)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${NODE_ENV==='production'?'; Secure':''}`)}function logout(res){res.setHeader('Set-Cookie',`sf_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${NODE_ENV==='production'?'; Secure':''}`)}
async function verifySteam(p){const b=new URLSearchParams();for(const[k,v]of p.entries())if(k.startsWith('openid.'))b.set(k,v);b.set('openid.mode','check_authentication');const r=await fetch(STEAM_OPENID,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'SkinForge/16.3'},body:b});return r.ok&&/is_valid:true/i.test(await r.text())}
async function profile(id){if(!STEAM_API_KEY)return{steamid:id,personaname:`Steam ${id.slice(-6)}`,profileurl:`https://steamcommunity.com/profiles/${id}/`,avatarfull:null};const u=new URL('https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/');u.searchParams.set('key',STEAM_API_KEY);u.searchParams.set('steamids',id);const r=await fetch(u);if(!r.ok)throw Error(`Steam Web API ${r.status}`);const d=await r.json();return d?.response?.players?.[0]||{steamid:id}}
async function initDb(){if(!DATABASE_URL)throw Error('DATABASE_URL missing');if(!db)db=new Pool({connectionString:DATABASE_URL,max:5,idleTimeoutMillis:30000,connectionTimeoutMillis:10000});await db.query(`CREATE TABLE IF NOT EXISTS user_data(steamid TEXT PRIMARY KEY,favorites JSONB NOT NULL DEFAULT '[]'::jsonb,portfolio JSONB NOT NULL DEFAULT '[]'::jsonb,alerts JSONB NOT NULL DEFAULT '[]'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await db.query(`CREATE TABLE IF NOT EXISTS site_admins(steamid TEXT PRIMARY KEY,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await db.query(`CREATE TABLE IF NOT EXISTS support_tickets(id BIGSERIAL PRIMARY KEY,steamid TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'other',subject TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',reply TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);return true}
async function ensureDb(){if(!dbReady)dbReady=initDb().catch(e=>{dbReady=null;throw e});return dbReady}
async function userData(id){await ensureDb();const r=await db.query('SELECT favorites,portfolio,alerts,updated_at FROM user_data WHERE steamid=$1',[id]);if(!r.rows.length)return{favorites:[],portfolio:[],alerts:[],updated_at:null};const x=r.rows[0];return{favorites:Array.isArray(x.favorites)?x.favorites:[],portfolio:Array.isArray(x.portfolio)?x.portfolio:[],alerts:Array.isArray(x.alerts)?x.alerts:[],updated_at:x.updated_at}}
function sane(v,n){return Array.isArray(v)?v.slice(0,n):[]}
async function saveUser(id,d){await ensureDb();const f=sane(d.favorites,2000),p=sane(d.portfolio,1000),a=sane(d.alerts,1000);await db.query(`INSERT INTO user_data(steamid,favorites,portfolio,alerts,updated_at) VALUES($1,$2::jsonb,$3::jsonb,$4::jsonb,NOW()) ON CONFLICT(steamid) DO UPDATE SET favorites=EXCLUDED.favorites,portfolio=EXCLUDED.portfolio,alerts=EXCLUDED.alerts,updated_at=NOW()`,[id,JSON.stringify(f),JSON.stringify(p),JSON.stringify(a)]);return{favorites:f,portfolio:p,alerts:a,updated_at:new Date().toISOString()}}
async function body(req){return await new Promise((resolve,reject)=>{let n=0,c=[];req.on('data',x=>{n+=x.length;if(n>1048576){reject(Error('Body too large'));req.destroy();return}c.push(x)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(c).toString('utf8')||'{}'))}catch(e){reject(Error('Invalid JSON'))}});req.on('error',reject)})}
async function isAdmin(id){if(!id)return false;await ensureDb();const r=await db.query('SELECT 1 FROM site_admins WHERE steamid=$1',[id]);return !!r.rows.length}
async function adminCount(){await ensureDb();const r=await db.query('SELECT COUNT(*)::int AS n FROM site_admins');return r.rows[0].n}
async function requireAdmin(req,res){const id=steamId(req);if(!id){json(res,401,{error:'Steam login required'});return null}if(!await isAdmin(id)){json(res,403,{error:'Admin access required'});return null}return id}
const WEAPON_PREFIXES=['AK-47','AUG','AWP','CZ75-Auto','Desert Eagle','Dual Berettas','FAMAS','Five-SeveN','G3SG1','Galil AR','Glock-18','M249','M4A1-S','M4A4','MAC-10','MAG-7','MP5-SD','MP7','MP9','Negev','Nova','P2000','P250','P90','PP-Bizon','R8 Revolver','SCAR-20','SG 553','SSG 08','Sawed-Off','Tec-9','UMP-45','USP-S','XM1014'];
const KNIFE_GLOVE_PREFIXES=['Bayonet','Bowie Knife','Butterfly Knife','Classic Knife','Falchion Knife','Flip Knife','Gut Knife','Huntsman Knife','Karambit','Kukri Knife','M9 Bayonet','Navaja Knife','Nomad Knife','Paracord Knife','Shadow Daggers','Skeleton Knife','Stiletto Knife','Survival Knife','Talon Knife','Ursus Knife','Bloodhound Gloves','Broken Fang Gloves','Driver Gloves','Hand Wraps','Hydra Gloves','Moto Gloves','Specialist Gloves','Sport Gloves'];
function catalogBaseName(name){return String(name||'').replace(/^Souvenir\s+/i,'').replace(/^★\s*StatTrak™\s+/i,'').replace(/^StatTrak™\s+/i,'').replace(/^★\s*/,'').trim()}
function isCatalogItem(item){const name=catalogBaseName(item?.market_hash_name);if(!name.includes(' | '))return false;return WEAPON_PREFIXES.some(p=>name.startsWith(p+' | '))||KNIFE_GLOVE_PREFIXES.some(p=>name.startsWith(p+' | '))}
function cleanCatalog(items){return Array.isArray(items)?items.filter(isCatalogItem):[]}
async function skinport(endpoint,params={}){const u=new URL('https://api.skinport.com'+endpoint);u.searchParams.set('app_id','730');u.searchParams.set('currency','USD');Object.entries(params).forEach(([k,v])=>v!==''&&u.searchParams.set(k,v));const k=u.toString(),hit=cache.get(k);if(hit&&Date.now()-hit.time<CACHE_MS)return hit.data;const r=await fetch(u,{headers:{Accept:'application/json','Accept-Encoding':'br'}});if(!r.ok)throw Error(`Skinport HTTP ${r.status}`);let d=await r.json();if(endpoint.includes('/v1/items')&&Array.isArray(d)){const rawCount=d.length;d=cleanCatalog(d);lastGoodItems=d;lastGoodItemsAt=new Date().toISOString();Object.assign(diag.skinport,{ok:true,last_success:lastGoodItemsAt,last_error:null,item_count:d.length,raw_item_count:rawCount})}cache.set(k,{time:Date.now(),data:d});return d}
function money(v){if(!v)return null;const n=parseFloat(String(v).replace(/[^0-9.,]/g,'').replace(/,/g,''));return Number.isFinite(n)?n:null}
async function steamPrice(name){const u=new URL('https://steamcommunity.com/market/priceoverview/');u.searchParams.set('appid','730');u.searchParams.set('currency','1');u.searchParams.set('country','US');u.searchParams.set('market_hash_name',name);const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0',Accept:'application/json'}});if(!r.ok)throw Error(`Steam HTTP ${r.status}`);const x=await r.json();return{success:!!x.success,lowest_price:money(x.lowest_price),median_price:money(x.median_price),volume:x.volume||null,raw:x}}
async function api(req,res,u){try{
if(u.pathname==='/api/user-data'){const id=steamId(req);if(!id)return json(res,401,{error:'Steam login required'});if(req.method==='GET')return json(res,200,{ok:true,steamid:id,...await userData(id)});if(req.method==='PUT'||req.method==='POST')return json(res,200,{ok:true,steamid:id,...await saveUser(id,await body(req))});return json(res,405,{error:'Method not allowed'})}
if(u.pathname==='/api/me'){const id=steamId(req);if(!id)return json(res,200,{authenticated:false});let p;try{p=await profile(id)}catch(e){p={steamid:id,personaname:`Steam ${id.slice(-6)}`,profileurl:`https://steamcommunity.com/profiles/${id}/`}}return json(res,200,{authenticated:true,profile:p,has_api_key:!!STEAM_API_KEY,is_admin:await isAdmin(id)})}
if(u.pathname==='/api/support/tickets'){const id=steamId(req);if(!id)return json(res,401,{error:'Steam login required'});await ensureDb();if(req.method==='GET'){const r=await db.query('SELECT id,category,subject,message,status,reply,created_at,updated_at FROM support_tickets WHERE steamid=$1 ORDER BY created_at DESC LIMIT 100',[id]);return json(res,200,{ok:true,tickets:r.rows})}if(req.method==='POST'){const d=await body(req),category=String(d.category||'other').slice(0,40),subject=String(d.subject||'').trim().slice(0,120),message=String(d.message||'').trim().slice(0,5000);if(!subject||!message)return json(res,400,{error:'Заполни тему и сообщение'});const r=await db.query('INSERT INTO support_tickets(steamid,category,subject,message) VALUES($1,$2,$3,$4) RETURNING id,category,subject,message,status,reply,created_at,updated_at',[id,category,subject,message]);return json(res,201,{ok:true,ticket:r.rows[0]})}return json(res,405,{error:'Method not allowed'})}
if(u.pathname==='/api/admin/me'){const id=steamId(req),count=await adminCount();return json(res,200,{authenticated:!!id,is_admin:id?await isAdmin(id):false,admin_exists:count>0,setup_enabled:!!ADMIN_SETUP_KEY})}
if(u.pathname==='/api/admin/claim'&&req.method==='POST'){const id=steamId(req);if(!id)return json(res,401,{error:'Сначала войди через Steam'});if(await adminCount())return json(res,409,{error:'Администратор уже назначен'});if(!ADMIN_SETUP_KEY)return json(res,503,{error:'Код настройки не задан'});const d=await body(req);if(!eq(String(d.key||''),ADMIN_SETUP_KEY))return json(res,403,{error:'Неверный код владельца'});await db.query('INSERT INTO site_admins(steamid) VALUES($1) ON CONFLICT DO NOTHING',[id]);return json(res,200,{ok:true,is_admin:true})}
if(u.pathname==='/api/admin/stats'){if(!await requireAdmin(req,res))return;await ensureDb();const[q1,q2,q3]=await Promise.all([db.query('SELECT COUNT(*)::int n FROM user_data'),db.query('SELECT COUNT(*)::int n FROM support_tickets'),db.query("SELECT COUNT(*)::int n FROM support_tickets WHERE status<>'closed'")]);return json(res,200,{ok:true,users:q1.rows[0].n,tickets:q2.rows[0].n,open_tickets:q3.rows[0].n,catalog_items:diag.skinport.item_count})}
if(u.pathname==='/api/admin/users'){if(!await requireAdmin(req,res))return;const r=await db.query('SELECT steamid,updated_at FROM user_data ORDER BY updated_at DESC NULLS LAST LIMIT 200');return json(res,200,{ok:true,users:r.rows})}
if(u.pathname==='/api/admin/tickets'&&req.method==='GET'){if(!await requireAdmin(req,res))return;const r=await db.query('SELECT id,steamid,category,subject,message,status,reply,created_at,updated_at FROM support_tickets ORDER BY created_at DESC LIMIT 300');return json(res,200,{ok:true,tickets:r.rows})}
if(/^\/api\/admin\/tickets\/\d+$/.test(u.pathname)&&req.method==='PUT'){if(!await requireAdmin(req,res))return;const id=Number(u.pathname.split('/').pop()),d=await body(req),status=['open','in_progress','closed'].includes(d.status)?d.status:'open',reply=String(d.reply||'').trim().slice(0,5000)||null;const r=await db.query('UPDATE support_tickets SET status=$1,reply=$2,updated_at=NOW() WHERE id=$3 RETURNING *',[status,reply,id]);if(!r.rows.length)return json(res,404,{error:'Обращение не найдено'});return json(res,200,{ok:true,ticket:r.rows[0]})}
if(u.pathname==='/api/ready')return json(res,200,{ok:true,service:'SkinForge v16.3',ready:true,database:!!DATABASE_URL,skinport_cached:Array.isArray(lastGoodItems),timestamp:new Date().toISOString()});
if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'SkinForge v16.3',env:NODE_ENV,database:!!DATABASE_URL,uptime_sec:Math.floor(process.uptime())});
if(u.pathname==='/api/status')return json(res,200,{ok:true,service:'SkinForge v16.3',uptime_sec:Math.floor(process.uptime()),now:new Date().toISOString(),node:process.version,database:{configured:!!DATABASE_URL},skinport:diag.skinport,steam:diag.steam,cache:{has_last_good_items:Array.isArray(lastGoodItems),last_good_items_at:lastGoodItemsAt,last_good_item_count:Array.isArray(lastGoodItems)?lastGoodItems.length:0}});
if(u.pathname==='/api/items-last-good')return Array.isArray(lastGoodItems)?json(res,200,cleanCatalog(lastGoodItems)):json(res,503,{error:'No successful Skinport snapshot cached yet'});
if(u.pathname==='/api/items'){let all;try{all=await skinport('/v1/items',{tradable:'1'})}catch(e){diag.skinport.ok=false;diag.skinport.last_error=String(e.message||e);if(!Array.isArray(lastGoodItems))throw e;all=lastGoodItems}all=cleanCatalog(all);const names=(u.searchParams.get('names')||'').split('|').filter(Boolean),wanted=new Set(names);return json(res,200,names.length?all.filter(x=>wanted.has(x.market_hash_name)):all)}
if(u.pathname==='/api/steam'){const name=u.searchParams.get('name');return name?json(res,200,await steamPrice(name)):json(res,400,{error:'name is required'})}
if(u.pathname==='/api/steam-batch'){const names=(u.searchParams.get('names')||'').split('|').filter(Boolean).slice(0,8),out=[];for(const name of names){try{out.push({name,...await steamPrice(name)})}catch(e){out.push({name,error:String(e.message||e)})}}return json(res,200,out)}
if(u.pathname==='/api/history')return json(res,200,await skinport('/v1/sales/history'));return json(res,404,{error:'API endpoint not found'})}catch(e){log('error','API error',{path:u.pathname,error:String(e.message||e)});return json(res,502,{error:'Request failed',detail:String(e.message||e)})}}
function staticFile(res,u){let rel=decodeURIComponent(u.pathname);if(rel==='/')rel='/index.html';if(rel==='/admin')rel='/admin.html';const f=path.normalize(path.join(ROOT,rel));if(!f.startsWith(ROOT))return send(res,403,'Forbidden','text/plain');fs.readFile(f,(e,b)=>{if(e)return send(res,404,'Not found','text/plain');const ext=path.extname(f).toLowerCase(),t={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.txt':'text/plain; charset=utf-8'};if(ext==='.html'){let h=b.toString('utf8');if(!h.includes('/cloud.js'))h=h.replace(/<\/body>/i,'<script src="/cloud.js?v=163"></script></body>');return send(res,200,h,t[ext])}send(res,200,b,t[ext]||'application/octet-stream')})}
http.createServer(async(req,res)=>{headers(res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/auth/steam'){const o=origin(req),st=state(),ret=new URL('/auth/steam/callback',o);ret.searchParams.set('state',st);const p=new URLSearchParams({'openid.ns':'http://specs.openid.net/auth/2.0','openid.mode':'checkid_setup','openid.return_to':ret.toString(),'openid.realm':o+'/','openid.identity':'http://specs.openid.net/auth/2.0/identifier_select','openid.claimed_id':'http://specs.openid.net/auth/2.0/identifier_select'});res.writeHead(302,{Location:`${STEAM_OPENID}?${p}`});return res.end()}if(u.pathname==='/auth/steam/callback'){try{if(!stateOK(u.searchParams.get('state'))||u.searchParams.get('openid.mode')!=='id_res'||!await verifySteam(u.searchParams))throw Error('Steam verification failed');const m=(u.searchParams.get('openid.claimed_id')||'').match(/steamcommunity\.com\/openid\/id\/(\d{17})/);if(!m)throw Error('SteamID missing');setSession(res,m[1]);res.writeHead(302,{Location:'/?steam=ok'});return res.end()}catch(e){log('warn','Steam login failed',{error:String(e.message||e)});res.writeHead(302,{Location:'/?steam=error'});return res.end()}}if(u.pathname==='/auth/logout'){logout(res);res.writeHead(302,{Location:'/'});return res.end()}if(u.pathname.startsWith('/api/'))return api(req,res,u);return staticFile(res,u)}).listen(PORT,HOST,async()=>{log('info','SkinForge v16.3 started',{url:`http://${HOST}:${PORT}`,env:NODE_ENV,database:!!DATABASE_URL});if(DATABASE_URL){try{await ensureDb();log('info','Postgres ready')}catch(e){log('error','Postgres init failed',{error:String(e.message||e)})}}});