(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null||!Number.isFinite(Number(n))?'—':'$'+Number(n).toFixed(2);
const params=()=>new URLSearchParams(location.search);
const getId=()=>params().get('id')||'';
const getHash=()=>params().get('hash')||'';
const originalFind=typeof window.findSkinById==='function'?window.findSkinById:null;
function exactLive(){const hash=getHash(),id=getId(),live=Array.isArray(window.LIVE_SKINS)?window.LIVE_SKINS:[];if(hash){const x=live.find(s=>s&&(String(s.marketHash||'')===hash||String(s.hash||'')===hash));if(x)return x}return live.find(s=>s&&s.id===id)||null}
window.findSkinById=function(id){const exact=exactLive();if(exact)return exact;if(originalFind){const x=originalFind(id);if(x)return x}const all=[...(Array.isArray(window.LIVE_SKINS)?window.LIVE_SKINS:[]),...(Array.isArray(window.SKINS)?window.SKINS:[])];const hash=getHash();return all.find(s=>s&&(s.id===id||(hash&&(String(s.marketHash||'')===hash||String(s.hash||'')===hash))))||null};
const current=()=>exactLive()||(typeof window.findSkinById==='function'?window.findSkinById(getId()):null);
function remember(s){if(!s)return;try{let a=JSON.parse(localStorage.getItem('aerox_recent_skins')||'[]');a=a.filter(x=>x.id!==s.id);a.unshift({id:s.id,hash:s.marketHash||s.hash||'',name:s.name,condition:s.condition,price:s.price,at:Date.now()});localStorage.setItem('aerox_recent_skins',JSON.stringify(a.slice(0,12)))}catch(e){}}
function buyUrlSkinport(s){return s.itemPage||s.marketPage||'https://skinport.com/market'}
function steamUrl(s){const h=s.marketHash||s.hash||s.name;return 'https://steamcommunity.com/market/listings/730/'+encodeURIComponent(h)}
function buildBuyRows(s){const prices=s.marketPrices||{},steam=Number(s.steam?.lowest_price)||Number(prices.steam?.buy)||0,csfloat=Number(prices.csfloat?.buy)||0,lisskins=Number(prices.lisskins?.buy)||0;return [
{id:'skinport',name:'Skinport',kind:'cash',status:'LIVE',price:Number(s.price)||0,url:buyUrlSkinport(s),note:'реальные деньги'},
{id:'csfloat',name:'CSFloat',kind:'cash',status:csfloat?'LIVE':'Цена временно недоступна',price:csfloat,url:'https://csfloat.com/',note:'минимальный листинг'},
{id:'lisskins',name:'Lis-Skins',kind:'cash',status:lisskins?'LIVE':'Цена временно недоступна',price:lisskins,url:'https://lis-skins.com/market/csgo/',note:'цена площадки'},
{id:'steam',name:'Steam Market',kind:'wallet',status:steam?(prices.steam?.price_type||'последние продажи'):'Цена временно недоступна',price:steam,url:steamUrl(s),note:'Steam Wallet'},
{id:'dmarket',name:'DMarket',kind:'cash',status:'Цена временно недоступна',price:0,disabled:true,url:'https://dmarket.com/ingame-items/item-list/csgo-skins',note:'нужен официальный API-ключ'}
]}
function injectBuy(s){const host=document.querySelector('#skinDetail > div:last-child');if(!host||host.querySelector('#buyCompare'))return;const rows=buildBuyRows(s);const wrap=document.createElement('section');wrap.className='buy-compare';wrap.id='buyCompare';wrap.innerHTML=`<div class="buy-compare-head"><div><div class="eyebrow">AEROX BUY COMPARE</div><h3>Где купить дешевле</h3><p>Автоматическое сравнение реальных доступных цен площадок.</p></div><div class="buy-best-result" id="buyBest">Считаем лучший вариант…</div></div><div class="buy-table"><div class="buy-row buy-labels"><span>Площадка</span><span>Цена</span><span>Экономия</span><span>Тип</span><span></span></div>${rows.map(r=>`<div class="buy-row${r.disabled?' market-unavailable':''}" data-buy-market="${r.id}"><span class="buy-title"><strong>${r.name}</strong><small>${r.status} • ${r.note}</small></span><label><small>Цена, $</small><input class="buy-price" type="number" min="0" step="0.01" value="${r.price||''}" placeholder="Нет данных" readonly></label><span class="buy-saving">${r.disabled?'Недоступно':'—'}</span><span>${r.kind==='wallet'?'Wallet':'Cash'}</span><a class="secondary buy-go" href="${r.url}" target="_blank" rel="noopener noreferrer">Купить</a></div>`).join('')}</div><div class="notice skin-v20-note">Skinport, CSFloat и Lis-Skins показывают cash-цены. Steam показывает среднюю цену последних продаж в Steam Wallet. DMarket подключим после получения официального API-ключа. После получения предмета может действовать 7-дневная торговая блокировка.</div>`;const sell=host.querySelector('#marketCompare');if(sell)sell.insertAdjacentElement('beforebegin',wrap);else host.appendChild(wrap);
const update=()=>{let list=[];wrap.querySelectorAll('[data-buy-market]').forEach(row=>{const p=Math.max(0,Number(row.querySelector('.buy-price')?.value)||0);row.classList.remove('buy-best');if(p>0)list.push({row,p,name:row.querySelector('.buy-title strong')?.textContent||''})});list.sort((a,b)=>a.p-b.p);const best=list[0],next=list[1];wrap.querySelectorAll('[data-buy-market]').forEach(row=>{const p=Math.max(0,Number(row.querySelector('.buy-price')?.value)||0),out=row.querySelector('.buy-saving');if(!p||!best){if(!row.classList.contains('market-unavailable'))out.textContent='—';return}if(row===best.row){out.textContent='Лучшая цена';return}const d=p-best.p,pct=p?d/p*100:0;out.textContent=`+${money(d)} (${pct.toFixed(1)}%)`});const bestBox=wrap.querySelector('#buyBest');if(best){best.row.classList.add('buy-best');const saving=next?Math.max(0,next.p-best.p):0;bestBox.innerHTML=`<small>Лучшая доступная цена</small><strong>${esc(best.name)} · ${money(best.p)}</strong>${saving>0?`<small>Экономия к следующей цене: ${money(saving)}</small>`:''}`}else bestBox.textContent='Цены временно недоступны'};update()}
function injectSummary(s){const host=document.querySelector('#skinDetail > div:last-child');if(!host||host.querySelector('.skin-v20-summary'))return;const hist=s.history||{},h7=hist.last_7_days||{},h30=hist.last_30_days||{};const avg7=Number(h7.avg)||null,avg30=Number(h30.avg)||null;const liq=Number(s.quantity)||0;const summary=document.createElement('div');summary.className='skin-v20-summary';summary.innerHTML=`<div class="stat-box"><span>Сейчас</span><strong>${money(s.price)}</strong><small>Skinport LIVE</small></div><div class="stat-box"><span>Средняя 7д</span><strong>${money(avg7)}</strong><small>${h7.volume!=null?`${h7.volume} продаж`:'нет данных'}</small></div><div class="stat-box"><span>Средняя 30д</span><strong>${money(avg30)}</strong><small>${h30.volume!=null?`${h30.volume} продаж`:'нет данных'}</small></div><div class="stat-box"><span>Ликвидность</span><strong>${liq.toLocaleString('ru-RU')}</strong><small>лотов Skinport</small></div>`;const firstNotice=host.querySelector('.notice');if(firstNotice)firstNotice.insertAdjacentElement('afterend',summary);else host.prepend(summary)}
function injectRelated(s){const main=document.querySelector('main.shell');if(!main||document.getElementById('relatedSkins'))return;const source=(window.LIVE_SKINS||[]).filter(x=>x&&x.id!==s.id&&x.weapon===s.weapon&&Number(x.price)>0).sort((a,b)=>Math.abs((a.price||0)-(s.price||0))-Math.abs((b.price||0)-(s.price||0))).slice(0,4);if(!source.length)return;const sec=document.createElement('section');sec.className='section related-wrap';sec.id='relatedSkins';sec.innerHTML=`<div class="section-head"><h2>Похожие скины</h2><a class="muted" href="catalog.html?q=${encodeURIComponent(s.weapon||'')}">Смотреть все →</a></div><div class="related-grid">${source.map(x=>`<a class="related-card" href="skin.html?id=${encodeURIComponent(x.id)}&hash=${encodeURIComponent(x.marketHash||x.hash||'')}"><img src="${x.img}" alt="${esc(x.name)}" loading="lazy"><strong>${esc(x.name)}</strong><small>${esc(x.condition||'')} • ${money(x.price)}</small></a>`).join('')}</div>`;main.appendChild(sec)}
function polishLabels(){document.querySelectorAll('.score-panel span').forEach(el=>{if(el.textContent.trim()==='SkinForge Deal Score')el.textContent='AEROX Deal Score'});document.querySelectorAll('a.card-btn[href*="skin.html"],a[href*="skin.html"].card-btn').forEach(a=>a.textContent='Аналитика');document.title=document.title.replace(/SkinForge/gi,'AEROX')}
let scheduled=false;function enhance(){scheduled=false;const s=current();if(!s)return;remember(s);injectSummary(s);injectBuy(s);injectRelated(s);polishLabels();const root=document.getElementById('skinDetail');if(root){root.style.visibility='visible';root.style.opacity='1'}}
function scheduleEnhance(){if(scheduled)return;scheduled=true;setTimeout(enhance,40)}
document.addEventListener('DOMContentLoaded',()=>{scheduleEnhance();const root=document.getElementById('skinDetail');if(root){new MutationObserver(()=>scheduleEnhance()).observe(root,{childList:true,subtree:true})}});document.addEventListener('skinforge-live-ready',scheduleEnhance);document.addEventListener('skinforge-history-ready',scheduleEnhance);document.addEventListener('skinforge-images-ready',scheduleEnhance);setTimeout(scheduleEnhance,1800);setTimeout(scheduleEnhance,5200);
})();
