(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n==null||!Number.isFinite(Number(n))?'—':'$'+Number(n).toFixed(2);
const params=()=>new URLSearchParams(location.search);
const getId=()=>params().get('id')||'';
const getHash=()=>params().get('hash')||'';
const originalFind=typeof window.findSkinById==='function'?window.findSkinById:null;
function exactLive(){const hash=getHash(),id=getId(),live=Array.isArray(window.LIVE_SKINS)?window.LIVE_SKINS:[];if(hash){const x=live.find(s=>s&&(String(s.marketHash||'')===hash||String(s.hash||'')===hash));return x||null}return live.find(s=>s&&s.id===id)||null}
window.findSkinById=function(id){const exact=exactLive();if(exact)return exact;if(originalFind){const x=originalFind(id);if(x)return x}const all=[...(Array.isArray(window.LIVE_SKINS)?window.LIVE_SKINS:[]),...(Array.isArray(window.SKINS)?window.SKINS:[])];const hash=getHash();return all.find(s=>s&&(s.id===id||(hash&&(String(s.marketHash||'')===hash||String(s.hash||'')===hash))))||null};
const current=()=>exactLive();
function remember(s){if(!s)return;try{let a=JSON.parse(localStorage.getItem('aerox_recent_skins')||'[]');a=a.filter(x=>x.id!==s.id);a.unshift({id:s.id,hash:s.marketHash||s.hash||'',name:s.name,condition:s.condition,price:s.price,at:Date.now()});localStorage.setItem('aerox_recent_skins',JSON.stringify(a.slice(0,12)))}catch(e){}}
function buyUrlSkinport(s){return s.itemPage||s.marketPage||'https://skinport.com/market'}
function steamUrl(s){const h=s.marketHash||s.hash||s.name;return 'https://steamcommunity.com/market/listings/730/'+encodeURIComponent(h)}
function buildBuyRows(s){const prices=s.marketPrices||{};if(s.marketStale)prices.skinport={...(prices.skinport||{}),stale:true};const steam=Number(s.steam?.lowest_price)||Number(prices.steam?.buy)||0,csfloat=Number(prices.csfloat?.buy)||0,lisskins=Number(prices.lisskins?.buy)||0;return [
{id:'skinport',name:'Skinport',kind:'cash',status:s.marketStale?'Сохранённая копия':'LIVE',price:Number(s.price)||0,url:buyUrlSkinport(s),note:'реальные деньги'},
{id:'csfloat',name:'CSFloat',kind:'cash',status:csfloat?marketDataLabel(prices.csfloat):'Цена временно недоступна',price:csfloat,url:'https://csfloat.com/',note:'минимальный листинг'},
{id:'lisskins',name:'Lis-Skins',kind:'cash',status:lisskins?marketDataLabel(prices.lisskins):'Цена временно недоступна',price:lisskins,url:'https://lis-skins.com/market/csgo/',note:'цена площадки'},
{id:'steam',name:'Steam Market',kind:'wallet',status:steam?(prices.steam?.price_type||'последние продажи')+' • '+marketDataLabel(prices.steam):'Цена временно недоступна',price:steam,url:steamUrl(s),note:'Steam Wallet'},
{id:'dmarket',name:'DMarket',kind:'cash',status:'Цена временно недоступна',price:0,disabled:true,url:'https://dmarket.com/ingame-items/item-list/csgo-skins',note:'нужен официальный API-ключ'}
]}
function injectBuy(s){const host=document.querySelector('#skinDetail > div:last-child');if(!host||host.querySelector('#buyCompare'))return;const rows=buildBuyRows(s);const wrap=document.createElement('section');wrap.className='buy-compare';wrap.id='buyCompare';wrap.innerHTML=`<div class="buy-compare-head"><div><div class="eyebrow">AEROX BUY COMPARE</div><h3>Где купить дешевле</h3><p>Автоматическое сравнение реальных доступных цен площадок.</p></div><div class="buy-best-result" id="buyBest">Считаем лучший вариант…</div></div><div class="buy-table"><div class="buy-row buy-labels"><span>Площадка</span><span>Цена</span><span>Экономия</span><span>Тип</span><span></span></div>${rows.map(r=>`<div class="buy-row${r.disabled?' market-unavailable':''}" data-buy-market="${r.id}" data-buy-kind="${r.kind}" data-stale="${s.marketPrices?.[r.id]?.stale===true}"><span class="buy-title"><strong>${r.name}</strong><small>${r.status} • ${r.note}</small></span><label><small>Цена, $</small><input class="buy-price" type="number" min="0" step="0.01" value="${r.price||''}" placeholder="Нет данных" readonly></label><span class="buy-saving">${r.disabled?'Недоступно':'—'}</span><span>${r.kind==='wallet'?'Wallet':'Cash'}</span><a class="secondary buy-go" href="${r.url}" target="_blank" rel="noopener noreferrer">Купить</a></div>`).join('')}</div><div class="notice skin-v20-note">Skinport, CSFloat и Lis-Skins показывают cash-цены. Steam показывает среднюю цену последних продаж в Steam Wallet. DMarket подключим после получения официального API-ключа. Средняя цена Steam и сохранённые копии после сбоя источника не участвуют в выборе лучшей покупки. После получения предмета может действовать торговая блокировка.</div>`;const sell=host.querySelector('#marketCompare');if(sell)sell.insertAdjacentElement('beforebegin',wrap);else host.appendChild(wrap);
const update=()=>{let list=[];wrap.querySelectorAll('[data-buy-market]').forEach(row=>{const p=Math.max(0,Number(row.querySelector('.buy-price')?.value)||0);row.classList.remove('buy-best');if(p>0&&row.dataset.buyKind==='cash'&&row.dataset.stale!=='true')list.push({row,p,name:row.querySelector('.buy-title strong')?.textContent||''})});list.sort((a,b)=>a.p-b.p);const best=list[0],next=list[1];wrap.querySelectorAll('[data-buy-market]').forEach(row=>{const p=Math.max(0,Number(row.querySelector('.buy-price')?.value)||0),out=row.querySelector('.buy-saving');if(row.dataset.buyKind==='wallet'){out.textContent='Средняя продаж, не предложение';return;}if(row.dataset.stale==='true'){out.textContent='Требует обновления';return;}if(!p||!best){if(!row.classList.contains('market-unavailable'))out.textContent='—';return}if(row===best.row){out.textContent='Лучшая цена';return}const d=p-best.p,pct=p?d/p*100:0;out.textContent=`+${money(d)} (${pct.toFixed(1)}%)`});const bestBox=wrap.querySelector('#buyBest');if(best){best.row.classList.add('buy-best');const saving=next?Math.max(0,next.p-best.p):0;bestBox.innerHTML=`<small>Минимальная cash-цена в сводке</small><strong>${esc(best.name)} · ${money(best.p)}</strong>${saving>0?`<small>Экономия к следующей цене: ${money(saving)}</small>`:''}`}else bestBox.textContent='Цены временно недоступны'};update()}
function injectDealVerifier(s){
 const host=document.querySelector('#skinDetail > div:last-child');if(!host||host.querySelector('#dealVerifier')||typeof verifiedDealSnapshot!=='function')return;
 const first=verifiedDealSnapshot(s),buyNames={skinport:'Skinport',csfloat:'CSFloat',lisskins:'Lis-Skins'},sellNames={csfloat:'CSFloat — ордер покупателя'};
 const buyOptions=Object.entries(first.buys||{}).filter(x=>x[1]).map(([id,p])=>`<option value="${id}" ${id===first.buyMarket?'selected':''}>${buyNames[id]} — ${money(p)}</option>`).join('');
 const sellOptions=Object.entries(first.sells||{}).filter(x=>x[1]).map(([id,p])=>`<option value="${id}" ${id===first.sellMarket?'selected':''}>${sellNames[id]} — ${money(p)}</option>`).join('');
 const sec=document.createElement('section');sec.id='dealVerifier';sec.className='deal-verifier';sec.innerHTML=`<div class="eyebrow">AEROX VERIFIED DEAL</div><h3>Проверка реальной сделки</h3><p>Считаем только по cash-предложению покупки и существующему ордеру покупателя.</p><div class="deal-form"><label>Где купить<select id="dealBuy">${buyOptions||'<option value="">Нет актуальных предложений</option>'}</select></label><label>Где продать<select id="dealSell">${sellOptions||'<option value="">Нет ордера покупателя</option>'}</select></label><label>Комиссия покупки, %<input id="dealBuyFee" type="number" min="0" max="99.99" step="0.1" value="0"></label><label>Комиссия продажи, %<input id="dealSellFee" type="number" min="0" max="99.99" step="0.1" value="2"></label><label>Резерв риска за 7 дней, %<input id="dealReserve" type="number" min="0" max="99.99" step="0.5" value="5"></label><label>Уведомить от прибыли, $<input id="dealAlertProfit" type="number" min="0" step="0.01" value="1"></label><label>Минимальный ROI, %<input id="dealAlertRoi" type="number" min="0" step="0.1" value="1"></label></div><div id="dealResult" class="deal-result"></div><button id="dealAlertSave" class="primary" type="button">🔔 Следить за прибыльной сделкой</button><p class="notice">Даже положительный расчёт не гарантирует прибыль: во время торговой блокировки ордер и цена могут измениться.</p>`;
 const sell=host.querySelector('#marketCompare');if(sell)sell.insertAdjacentElement('beforebegin',sec);else host.appendChild(sec);
 const calculate=()=>{const d=verifiedDealSnapshot(s,{buyMarket:sec.querySelector('#dealBuy').value,sellMarket:sec.querySelector('#dealSell').value,buyFee:sec.querySelector('#dealBuyFee').value,sellFee:sec.querySelector('#dealSellFee').value,reservePct:sec.querySelector('#dealReserve').value}),out=sec.querySelector('#dealResult');if(!d.ok){out.className='deal-result deal-none';out.innerHTML=`<strong>Недостаточно данных</strong><span>${esc(d.reason)}</span>`;return d}out.className='deal-result '+(d.positive?'deal-positive':'deal-negative');out.innerHTML=`<div><small>Покупка с комиссией</small><strong>${money(d.cost)}</strong></div><div><small>После продажи</small><strong>${money(d.net)}</strong></div><div><small>Резерв риска</small><strong>−${money(d.reserve)}</strong></div><div><small>Расчётный результат</small><strong>${d.profit>=0?'+':''}${money(d.profit)} · ${d.roi.toFixed(1)}%</strong></div><p>${d.positive?'Есть положительная маржа по текущему ордеру':'После комиссий и резерва прибыли нет'}</p>`;return d};
 sec.querySelectorAll('select,input').forEach(x=>x.addEventListener('input',calculate));sec.querySelector('#dealAlertSave').addEventListener('click',()=>{const d=calculate();if(!d.ok){sec.querySelector('#dealAlertSave').textContent='Недостаточно данных для уведомления';return}saveProfitAlert(s,sec.querySelector('#dealAlertProfit').value,sec.querySelector('#dealAlertRoi').value,sec.querySelector('#dealReserve').value);sec.querySelector('#dealAlertSave').textContent='✓ Умное уведомление сохранено'});calculate();
}
function injectPriceReport(s){
 const host=document.querySelector('#skinDetail > div:last-child'),actions=host?.querySelector('.quick-actions');if(!host||!actions||actions.querySelector('.price-report-button'))return;document.getElementById('priceReportDialog')?.remove();
 const button=document.createElement('button');button.className='ghost price-report-button';button.type='button';button.textContent='⚑ Сообщить об ошибке цены';actions.appendChild(button);
 const dialog=document.createElement('dialog');dialog.id='priceReportDialog';dialog.className='price-report-dialog';dialog.innerHTML=`<form method="dialog" class="price-report-card"><div class="price-report-head"><div><div class="eyebrow">AEROX PRICE CHECK</div><h3>Сообщить об ошибке цены</h3></div><button type="button" class="price-report-close" aria-label="Закрыть">×</button></div><p>Сообщение попадёт владельцу AEROX. Укажи цену, которую видишь непосредственно на площадке.</p><label>Площадка<select id="reportMarket"><option value="skinport">Skinport</option><option value="csfloat">CSFloat</option><option value="lisskins">Lis-Skins</option><option value="steam">Steam</option><option value="other">Другая</option></select></label><label>Цена на площадке, $<input id="reportObserved" type="number" min="0" max="1000000" step="0.01" placeholder="Например, 31.50"></label><label>Что не так?<select id="reportReason"><option value="wrong">Цена отличается</option><option value="stale">Цена устарела</option><option value="missing">Цена отсутствует</option><option value="unavailable">Предложение недоступно</option><option value="other">Другое</option></select></label><label>Комментарий<textarea id="reportNote" maxlength="1000" placeholder="Что именно ты увидел на площадке?"></textarea></label><div class="price-report-actions"><button type="button" class="secondary price-report-cancel">Отмена</button><button type="submit" class="primary" id="reportSubmit">Отправить</button></div><div id="reportMessage" class="price-report-message"></div><small>Вход через Steam не обязателен. Мы не сохраняем IP в отчёте.</small></form>`;document.body.appendChild(dialog);
 const close=()=>dialog.close();dialog.querySelector('.price-report-close').onclick=close;dialog.querySelector('.price-report-cancel').onclick=close;button.onclick=()=>{window.AeroxAnalytics?.track('price_report_open',{item_name:s.name});dialog.showModal()};
 dialog.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const submit=dialog.querySelector('#reportSubmit'),message=dialog.querySelector('#reportMessage'),market=dialog.querySelector('#reportMarket').value,prices=s.marketPrices||{},sitePrice=market==='skinport'?s.price:market==='csfloat'?prices.csfloat?.buy:market==='lisskins'?prices.lisskins?.buy:market==='steam'?(s.steam?.lowest_price||prices.steam?.buy):null;submit.disabled=true;message.textContent='Отправляем…';try{const r=await fetch('/api/price-reports',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitor_id:typeof analyticsVisitor==='function'?analyticsVisitor():'',item_name:s.name,market,site_price:sitePrice,observed_price:dialog.querySelector('#reportObserved').value,reason:dialog.querySelector('#reportReason').value,note:dialog.querySelector('#reportNote').value})}),d=await r.json();if(!r.ok)throw Error(d.error||'Не удалось отправить');window.AeroxAnalytics?.track('price_report_submit',{item_name:s.name,market});message.textContent=`Спасибо! Сообщение #${d.report.id} принято.`;submit.textContent='Отправлено';setTimeout(close,1300)}catch(err){message.textContent=err.message;submit.disabled=false}});
}
function injectSummary(s){const host=document.querySelector('#skinDetail > div:last-child');if(!host||host.querySelector('.skin-v20-summary'))return;const hist=s.history||{},h7=hist.last_7_days||{},h30=hist.last_30_days||{};const avg7=Number(h7.avg)||null,avg30=Number(h30.avg)||null;const liq=Number(s.quantity)||0;const summary=document.createElement('div');summary.className='skin-v20-summary';summary.innerHTML=`<div class="stat-box"><span>Сейчас</span><strong>${money(s.price)}</strong><small>Skinport LIVE</small></div><div class="stat-box"><span>Средняя 7д</span><strong>${money(avg7)}</strong><small>${h7.volume!=null?`${h7.volume} продаж`:'нет данных'}</small></div><div class="stat-box"><span>Средняя 30д</span><strong>${money(avg30)}</strong><small>${h30.volume!=null?`${h30.volume} продаж`:'нет данных'}</small></div><div class="stat-box"><span>Ликвидность</span><strong>${liq.toLocaleString('ru-RU')}</strong><small>лотов Skinport</small></div>`;const firstNotice=host.querySelector('.notice');if(firstNotice)firstNotice.insertAdjacentElement('afterend',summary);else host.prepend(summary)}
function injectRelated(s){const main=document.querySelector('main.shell');if(!main)return;const existing=document.getElementById('relatedSkins');if(existing){existing.querySelectorAll('.related-card img').forEach(img=>{const match=(window.LIVE_SKINS||[]).find(x=>String(x?.name||'')===img.alt);if(match?.img){if(img.src!==match.img)img.src=match.img;img.style.opacity='1'}});return}const source=(window.LIVE_SKINS||[]).filter(x=>x&&x.id!==s.id&&x.weapon===s.weapon&&Number(x.price)>0).sort((a,b)=>Math.abs((a.price||0)-(s.price||0))-Math.abs((b.price||0)-(s.price||0))).slice(0,4);if(!source.length)return;const sec=document.createElement('section');sec.className='section related-wrap';sec.id='relatedSkins';sec.innerHTML=`<div class="section-head"><h2>Похожие скины</h2><a class="muted" href="catalog.html?q=${encodeURIComponent(s.weapon||'')}">Смотреть все →</a></div><div class="related-grid">${source.map(x=>`<a class="related-card" href="skin.html?id=${encodeURIComponent(x.id)}&hash=${encodeURIComponent(x.marketHash||x.hash||'')}"><img src="${x.img}" alt="${esc(x.name)}" loading="lazy"><strong>${esc(x.name)}</strong><small>${esc(x.condition||'')} • ${money(x.price)}</small></a>`).join('')}</div>`;main.appendChild(sec)}
function polishLabels(){document.querySelectorAll('.score-panel span').forEach(el=>{if(el.textContent.trim()==='SkinForge Deal Score')el.textContent='AEROX Deal Score'});document.querySelectorAll('a.card-btn[href*="skin.html"],a[href*="skin.html"].card-btn').forEach(a=>a.textContent='Аналитика');document.title=document.title.replace(/SkinForge/gi,'AEROX')}
let scheduled=false;function enhance(){scheduled=false;const s=current();if(!s)return;remember(s);injectSummary(s);injectBuy(s);injectDealVerifier(s);injectPriceReport(s);injectRelated(s);polishLabels();const root=document.getElementById('skinDetail');if(root){root.style.visibility='visible';root.style.opacity='1'}}
function scheduleEnhance(){if(scheduled)return;scheduled=true;setTimeout(enhance,40)}
document.addEventListener('DOMContentLoaded',()=>{scheduleEnhance();const root=document.getElementById('skinDetail');if(root){new MutationObserver(()=>scheduleEnhance()).observe(root,{childList:true,subtree:true})}});document.addEventListener('skinforge-live-ready',scheduleEnhance);document.addEventListener('skinforge-history-ready',scheduleEnhance);document.addEventListener('skinforge-images-ready',scheduleEnhance);setTimeout(scheduleEnhance,1800);setTimeout(scheduleEnhance,5200);
})();
